### ISSUE TITLE
Constraint name wrong in altercols branch

### ISSUE THREAD

**Issue by carlkesselman** [informatics-isi-edu/deriva-py#85]
For a catalog c, I get the following:
```
c
Out[179]: <deriva.core.ermrest_catalog.ErmrestCatalog at 0x113e23780>
c.getCatalogModel().schemas['TestSchema'].tables['Table1'].keys[0].name
Out[180]: (<deriva.core.ermrest_model.Schema at 0x114154940>, 'Table1_RIDkey1')

c.getCatalogModel().schemas['TestSchema'].tables['Table1'].keys[0].names
Out[190]: [['TestSchema', 'Table1_RIDkey1']]
c.getCatalogModel().schemas['TestSchema'].tables['Table1'].keys[('TestSchema', 'Table1_RIDkey1')]
Traceback (most recent call last):
  File "/Users/carl/.conda/envs/deriva/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3325, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-191-82d096cd1809>", line 1, in <module>
    c.getCatalogModel().schemas['TestSchema'].tables['Table1'].keys[('TestSchema', 'Table1_RIDkey1')]
  File "/Users/carl/Repos/Projects/deriva-py/deriva/core/ermrest_config.py", line 505, in __getitem__
    return self.elements[idx]
KeyError: ('TestSchema', 'Table1_RIDkey1')
```

I think that the first element of the key name should be a string, not a Schema object.

**Comment by karlcz** [comment]
Actually this is an intended part of the currently in-progress
refactor, to purge different string copies laying around throughout
the object tree. This simplified handling of schema rename operations,
for example.

This is not necessarily the final configuration though. I intend to
revisit how/whether the Key.name and ForeignKey.name field is retained
and/or computed.  I may also change the way the Table.keys and
Table.foreign_keys containers are keyed for lookups.
